on:
  workflow_dispatch:
  schedule:
    # this job is very slow AND expensive
    - cron: '0 5 * * 5' # every Friday at 5:00 AM
    # so a few hours after the wikipedia paragraphs job

jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - run: node --version
      - run: yarn --version
      - run: yarn install --frozen-lockfile
      - run: yarn start update_wikipedia_summaries
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto commit of wikipedia paragraphs
