on:
  # push:
  #   branches:
  #     - main
  #     - master
  workflow_dispatch: # allow to trigger it manually
  schedule:
    - cron: '0 3 * * *' # every day at 3h

jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - run: node --version
      - run: yarn --version
      - run: yarn install --frozen-lockfile
      - run: yarn start update_nosdeputes_basic_data --latestLegislatureOnly
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto commit of basic deputes data from NosDeputes.fr
