on:
  workflow_dispatch:
  ### 2026-01 : disabling all jobs of this project
  # schedule:
  #   # this job is very slow, we don't need to run it that often
  #   - cron: '15 2 * * 5' # every Friday at 2:15 AM (so a bit after the wikipedia urls job)

jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - run: node --version
      - run: yarn --version
      - run: yarn install --frozen-lockfile
      - run: yarn start update_wikipedia_paragraphs
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto commit of wikipedia paragraphs
